services:
  control-plane:
    image: control-plane:latest
    build: .
    user: 1000:1000
    container_name: control-plane
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./streams:/streams
      - ./pb_data:/pb_data